using System;
using System.Collections.Generic;
using System.Text;

namespace ZOI.BAL.Utilities
{
    public static class CAMSTransactionFileHeader
    {
        public const string amc_code = "amc_code";
        public const string folio_no = "folio_no";
        public const string prodcode = "prodcode";
        public const string scheme = "scheme";
        public const string inv_name = "inv_name";
        public const string trxntype = "trxntype";
        public const string trxnno = "trxnno";
        public const string trxnmode = "trxnmode";
        public const string trxnstat = "trxnstat";
        public const string usercode = "usercode";
        public const string usrtrxno = "usrtrxno";
        public const string traddate = "traddate";
        public const string postdate = "postdate";
        public const string purprice = "purprice";
        public const string units = "units";
        public const string amount = "amount";
        public const string brokcode = "brokcode";
        public const string subbrok = "subbrok";
        public const string brokperc = "brokperc";
        public const string brokcomm = "brokcomm";
        public const string altfolio = "altfolio";
        public const string rep_date = "rep_date";
        public const string time1 = "time1";
        public const string trxnsubtyp = "trxnsubtyp";
        public const string application_no = "application_no";
        public const string trxn_nature = "trxn_nature";
        public const string tax = "tax";
        public const string total_tax = "total_tax";
        public const string te_15h = "te_15h";
        public const string micr_no = "micr_no";
        public const string remarks = "remarks";
        public const string swflag = "swflag";
        public const string old_folio = "old_folio";
        public const string seq_no = "seq_no";
        public const string reinvest_flag = "reinvest_flag";
        public const string mult_brok = "mult_brok";
        public const string stt = "stt";
        public const string location = "location";
        public const string scheme_type = "scheme_type";
        public const string tax_status = "tax_status";
        public const string load = "load";
        public const string scanrefno = "scanrefno";
        public const string pan = "pan";
        public const string inv_iin = "inv_iin";
        public const string targ_src_scheme = "targ_src_scheme";
        public const string trxn_type_flag = "trxn_type_flag";
        public const string ticob_trtype = "ticob_trtype";
        public const string ticob_trno = "ticob_trno";
        public const string ticob_posted_date = "ticob_posted_date";
        public const string dp_id = "dp_id";
        public const string trxn_charges = "trxn_charges";
        public const string eligib_amt = "eligib_amt";
        public const string src_of_txn = "src_of_txn";
        public const string trxn_suffix = "trxn_suffix";
        public const string siptrxnno = "siptrxnno";
        public const string ter_location = "ter_location";
        public const string euin = "euin";
        public const string euin_valid = "euin_valid";
        public const string euin_opted = "euin_opted";
        public const string sub_brk_arn = "sub_brk_arn";
        public const string exch_dc_flag = "exch_dc_flag";
        public const string src_brk_code = "src_brk_code";
        public const string sys_regn_date = "sys_regn_date";
        public const string ac_no = "ac_no";
        public const string bank_name = "bank_name";
        public const string reversal_code = "reversal_code";
        public const string exchange_flag = "exchange_flag";
        public const string ca_initiated_date = "ca_initiated_date";
        public const string gst_state_code = "gst_state_code";
        public const string igst_amount = "igst_amount";
        public const string cgst_amount = "cgst_amount";
        public const string sgst_amount = "sgst_amount";
        public const string rev_remark = "rev_remark";
        public const string original_trxnno = "original_trxnno";
    }
}
